-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 19:26:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ATMSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ATMSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATMSystem` DEFAULT CHARACTER SET utf8 ;
USE `ATMSystem` ;

-- -----------------------------------------------------
-- Table `ATMSystem`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATMSystem`.`Persona` (
  `id_Persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(150) NULL,
  `apellido` NVARCHAR(150) NULL,
  `fechaNacimiento` DATE NULL,
  `dui` INT NULL,
  `correo` NVARCHAR(100) NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id_Persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATMSystem`.`CuentaBancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATMSystem`.`CuentaBancaria` (
  `id_CuentaBancaria` INT NOT NULL AUTO_INCREMENT,
  `id_Persona` INT NOT NULL,
  `n_CuentaBancaria` INT NULL,
  `saldo` DOUBLE NULL DEFAULT 00.00,
  `usuario` NVARCHAR(50) NULL,
  `pin` INT NULL,
  PRIMARY KEY (`id_CuentaBancaria`),
  INDEX `fk_CuentaBancaria_Persona_idx` (`id_Persona` ASC),
  CONSTRAINT `fk_CuentaBancaria_Persona`
    FOREIGN KEY (`id_Persona`)
    REFERENCES `ATMSystem`.`Persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATMSystem`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATMSystem`.`Transacciones` (
  `id_Transacciones` INT NOT NULL AUTO_INCREMENT,
  `id_CuentaBancaria` INT NOT NULL,
  `detalleTransaccion` NVARCHAR(500) NULL,
  `fechaTransaccion` DATE NULL,
  `movimiento` DOUBLE NULL DEFAULT 00.00,
  PRIMARY KEY (`id_Transacciones`),
  INDEX `fk_Transacciones_CuentaBancaria1_idx` (`id_CuentaBancaria` ASC),
  CONSTRAINT `fk_Transacciones_CuentaBancaria1`
    FOREIGN KEY (`id_CuentaBancaria`)
    REFERENCES `ATMSystem`.`CuentaBancaria` (`id_CuentaBancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
